apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - agnostics/gateway.yaml
  - agnostics/cert-manager.yaml
  - agnostics/cluster-autoscaler.yaml
  - agnostics/cnpg.yaml
  # TODO: Move CiliumClusterwideNetworkPolicy/allow-pod-to-pod-via-gateway from
  # apps/jupyterhub/base/network_policy.yaml to here
  - agnostics/default-network-policy.yaml
  - agnostics/external-dns.yaml
  - agnostics/external-secrets.yaml
  - agnostics/kare-dns.yaml
  - agnostics/loadbalancer.yaml
  # - agnostics/nginx.yaml
  - agnostics/secret-store.yaml
  - agnostics/storage-class.yaml
  # - agnostics/object-storage.yaml
  # - agnostics/ad.yaml
  - federation/cr8tor.yaml
  - federation/netbird.yaml
  - identity/keycloak.yaml
  - identity/backend.yaml
  - workspaces/jupyterhub.yaml
  - workspaces/guacamole.yaml
  # - workspaces/gitea.yaml
  # - observability/observability-metrics.yaml

patches:
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
  - target:
      kind: ApplicationSet
    patch: |-
      - op: add
        path: /spec/ignoreApplicationDifferences
        value:
          - jsonPointers:
              - /spec/syncPolicy
              #- /spec/source/targetRevision
              
